/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BookDatabase__factory } from "./BookDatabase__factory";
export { HelloWorld__factory } from "./HelloWorld__factory";
