/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProtoCoin } from "./ProtoCoin";
export * as factories from "./factories";
export { ProtoCoin__factory } from "./factories/ProtoCoin__factory";
